# Generated by Django 5.2.4 on 2025-09-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donor_details_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_acuity', models.CharField(blank=True, max_length=20, null=True)),
                ('corneal_thickness', models.FloatField(blank=True, null=True)),
                ('iop', models.FloatField(blank=True, null=True)),
                ('creatinine', models.FloatField(blank=True, null=True)),
                ('bun', models.FloatField(blank=True, null=True)),
                ('gfr', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('ast', models.FloatField(blank=True, null=True)),
                ('bilirubin', models.FloatField(blank=True, null=True)),
                ('albumin', models.FloatField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('hla_typing', models.CharField(blank=True, max_length=100, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
                ('wbc', models.IntegerField(blank=True, null=True)),
                ('platelets', models.IntegerField(blank=True, null=True)),
                ('bp', models.CharField(blank=True, max_length=15, null=True)),
                ('ecg', models.CharField(blank=True, max_length=50, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('hiv', models.CharField(blank=True, max_length=10, null=True)),
                ('hbv', models.CharField(blank=True, max_length=10, null=True)),
                ('hcv', models.CharField(blank=True, max_length=10, null=True)),
                ('vdrl', models.CharField(blank=True, max_length=10, null=True)),
                ('reports', models.FileField(blank=True, null=True, upload_to='test_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
