# Generated by Django 5.2.6 on 2025-09-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0019_organapplicationmodels_block1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodels',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
